### ISSUE TITLE
but will it work for online CategoricalNB?

### ISSUE THREAD

**Issue by Sandy4321** [ginagigo123/Naive-Bayes-and-Online-learning#1]
great code

but will it work for online CategoricalNB

https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.CategoricalNB.html

**Comment by ginagigo123** [comment]
Hi Sandy,

Sure it will work for online CategoricalNB. But my `Online_learning.py` is not related to `Naive_Bayes.py`.

In `Naive_Bayes.py`, I used MNIST. There would be 10 categories.
As for the online learning part, you could implement it, maybe like recalculating the probability.

**Comment by Sandy4321** [comment]
do you know moody else code during this?

**Comment by ginagigo123** [comment]
> do you know moody else code during this?

Sorry, what do you mean?
